# Generated by Django 4.0 on 2024-04-03 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_user_groups_alter_user_user_permissions_and_more'),
        ('catalog', '0004_alter_version_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='user.user', verbose_name='Владелец'),
            preserve_default=False,
        ),
    ]
