# Generated by Django 5.0.2 on 2024-04-03 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verification_token',
            field=models.CharField(default=1, max_length=255, verbose_name='Токен верификации'),
            preserve_default=False,
        ),
    ]
