# Generated by Django 5.0.2 on 2024-04-03 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_verification_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
